/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLNV;

import java.awt.JobAttributes;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import javax.management.modelmbean.ModelMBean;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Quan_Ly_Nhan_Vien extends javax.swing.JFrame {

    ArrayList<Nguoi> a = new ArrayList<>();
    ArrayList<Nguoi> b = new ArrayList<>();
    ArrayList<Nguoi> c = new ArrayList<>();
    DefaultTableModel model; //tao doi tuong 
    DanhSachNhanVien x = new DanhSachNhanVien();

    /**
     * Creates new form Quan_Ly_Nhan_Vien
     */
    public Quan_Ly_Nhan_Vien() {
        initComponents();
        model = new DefaultTableModel();//ok
        this.setLocationRelativeTo(null);//cho no o giua
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//dong dc dau x 
        this.setResizable(false);
        model.setColumnIdentifiers(new Object[]{
            "ID", "TEN", "NGAY SINH", "GIOI TINH", "DIEN THOAI", "CHUC VU", "SO NGAY LAM", "SO NGAY DI TRE",
            "TANG CA", "PHU CAP", "TIEN LUONG"
        });
        tableHienThi.setModel(model);
        btTangDan.setVisible(false);
        btGiamDan.setVisible(false);
        btTheoTen.setVisible(false);
        btSoNgayLam.setVisible(false);
        btGioiTinhNam.setVisible(false);
        btChucVuCao.setVisible(false);
        btGioiTInhNu.setVisible(false);
        btChucVuThap.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHienThi = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtSoNgayLam = new javax.swing.JTextField();
        btThemMoi = new javax.swing.JButton();
        btNhapLai = new javax.swing.JButton();
        btThongKe = new javax.swing.JButton();
        btDocFile = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSapXep = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtSoNgayDiTre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSoGioTangCa = new javax.swing.JTextField();
        btLamMoi = new javax.swing.JButton();
        gioiTinhNam = new javax.swing.JRadioButton();
        gioiTinhNu = new javax.swing.JRadioButton();
        cbbChucVu = new javax.swing.JComboBox<>();
        btThoat = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();
        btLuuFile = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtThongBao = new javax.swing.JTextArea();
        btTangDan = new javax.swing.JButton();
        btGiamDan = new javax.swing.JButton();
        tfTimKiem = new javax.swing.JTextField();
        btTheoTen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btChucVuCao = new javax.swing.JButton();
        btGioiTinhNam = new javax.swing.JButton();
        btSoNgayLam = new javax.swing.JButton();
        btThoiViec = new javax.swing.JButton();
        btGioiTInhNu = new javax.swing.JButton();
        btChucVuThap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("TÊN NHÂN VIÊN:");

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NGÀY SINH:");

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("GIỚI TÍNH:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("CHỨC VỤ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("SỐ ĐIỆN THOẠI:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("MÃ NHÂN VIÊN:");

        txtDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("QUẢN LÝ NHÂN VIÊN ");

        tableHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableHienThi);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("SỐ NGÀY LÀM:");

        txtSoNgayLam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoNgayLam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoNgayLamFocusLost(evt);
            }
        });
        txtSoNgayLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNgayLamActionPerformed(evt);
            }
        });

        btThemMoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\themMoi.png")); // NOI18N
        btThemMoi.setText("THÊM MỚI");
        buttonGroup3.add(btThemMoi);
        btThemMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btThemMoiFocusLost(evt);
            }
        });
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });

        btNhapLai.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\nhapLao.png")); // NOI18N
        btNhapLai.setText("NHẬP LẠI");
        buttonGroup3.add(btNhapLai);
        btNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapLaiActionPerformed(evt);
            }
        });

        btThongKe.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\ThongKe.png")); // NOI18N
        btThongKe.setText("THỐNG KÊ");
        buttonGroup3.add(btThongKe);
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });

        btDocFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\docFile.png")); // NOI18N
        btDocFile.setText("ĐỌC FILE");
        buttonGroup3.add(btDocFile);
        btDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocFileActionPerformed(evt);
            }
        });

        btXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\Xoa.png")); // NOI18N
        btXoa.setText("XÓA ");
        buttonGroup3.add(btXoa);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSapXep.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\sapXep.png")); // NOI18N
        btSapXep.setText("SẮP XẾP");
        buttonGroup3.add(btSapXep);
        btSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSapXepActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("SỐ NGÀY ĐI TRỄ:");

        txtSoNgayDiTre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("SỐ GIỜ TĂNG CA:");

        txtSoGioTangCa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btLamMoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\lamMoi.png")); // NOI18N
        btLamMoi.setText("LÀM MỚI");
        buttonGroup3.add(btLamMoi);
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });

        buttonGroup1.add(gioiTinhNam);
        gioiTinhNam.setSelected(true);
        gioiTinhNam.setText("Nam");

        buttonGroup1.add(gioiTinhNu);
        gioiTinhNu.setText("Nu");
        gioiTinhNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gioiTinhNuActionPerformed(evt);
            }
        });

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thuc tap sinh", "Nhan vien", "Pho Phong", "Truong phong", "Giam doc", " " }));
        cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucVuActionPerformed(evt);
            }
        });

        btThoat.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\Thoat.png")); // NOI18N
        btThoat.setText("THOÁT");
        buttonGroup3.add(btThoat);
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        btTimKiem.setBackground(new java.awt.Color(51, 51, 51));
        btTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\timKiem.png")); // NOI18N
        btTimKiem.setText("TÌM KIẾM THEO MÃ");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        btLuuFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\ghiFile.png")); // NOI18N
        btLuuFile.setText("LƯU FILE");
        buttonGroup3.add(btLuuFile);
        btLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuFileActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("BẢNG THÔNG BÁO");

        btClear.setBackground(new java.awt.Color(0, 0, 0));
        btClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btClear.setForeground(new java.awt.Color(255, 255, 255));
        btClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\lamMoi.png")); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        jtThongBao.setColumns(20);
        jtThongBao.setRows(5);
        jScrollPane2.setViewportView(jtThongBao);

        btTangDan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\TangDan.png")); // NOI18N
        btTangDan.setText("TĂNG DẦN");
        btTangDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTangDanActionPerformed(evt);
            }
        });

        btGiamDan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\GiaMDan1.png")); // NOI18N
        btGiamDan.setText("GIẢM DẦN");
        btGiamDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGiamDanActionPerformed(evt);
            }
        });

        tfTimKiem.setToolTipText("Nhập mã nhân viên");
        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });

        btTheoTen.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\sapXepTheoTen.png")); // NOI18N
        btTheoTen.setText("THEO TÊN");
        btTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTheoTenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Đây là bản quyền của : Đoàn Võ Văn Trọng");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\CK.png")); // NOI18N

        btChucVuCao.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\CAOTHAP.png")); // NOI18N
        btChucVuCao.setText("CV CAO-THAP");
        btChucVuCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChucVuCaoActionPerformed(evt);
            }
        });

        btGioiTinhNam.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\NAM_NU.png")); // NOI18N
        btGioiTinhNam.setText("NAM-NỮ");
        btGioiTinhNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGioiTinhNamActionPerformed(evt);
            }
        });

        btSoNgayLam.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\Theongay.png")); // NOI18N
        btSoNgayLam.setText("SỐ NGÀY LÀM");
        btSoNgayLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSoNgayLamActionPerformed(evt);
            }
        });

        btThoiViec.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\LoaiBo.png")); // NOI18N
        btThoiViec.setText("THÔI VIỆC");
        buttonGroup3.add(btThoiViec);
        btThoiViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoiViecActionPerformed(evt);
            }
        });

        btGioiTInhNu.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\NU_NAM.png")); // NOI18N
        btGioiTInhNu.setText("NỮ-NAM");
        btGioiTInhNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGioiTInhNuActionPerformed(evt);
            }
        });

        btChucVuThap.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Pictures\\Ảnh tải xuống\\THAPCAO.png")); // NOI18N
        btChucVuThap.setText("CV THẤP-CAO");
        btChucVuThap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChucVuThapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSoNgayDiTre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSoNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(2, 2, 2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gioiTinhNam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gioiTinhNu))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoGioTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(54, 54, 54)
                                        .addComponent(btClear))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btGiamDan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btGioiTinhNam, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(btChucVuThap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btThoiViec, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(btSapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btTheoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btTangDan))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btGioiTInhNu)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btSoNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(btChucVuCao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btNhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btLuuFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDocFile, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1124, 1124, 1124)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gioiTinhNam)
                                    .addComponent(gioiTinhNu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoNgayDiTre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoGioTangCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btGioiTinhNam)
                                    .addComponent(btChucVuThap))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btGiamDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btNhapLai)
                                    .addGap(18, 18, 18)
                                    .addComponent(btThongKe))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btThemMoi)
                                    .addGap(18, 18, 18)
                                    .addComponent(btLamMoi)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btXoa)
                                    .addComponent(btSapXep))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btThoiViec)
                                    .addComponent(btThoat)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btDocFile)
                                .addGap(18, 18, 18)
                                .addComponent(btLuuFile))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btTangDan)
                                    .addComponent(btChucVuCao))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btGioiTInhNu)
                                        .addComponent(btSoNgayLam))
                                    .addComponent(btTheoTen))))
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    int n = 0;
    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        // TODO add your handling code here:
        //them moi 
        int dem = 0;
        String ma, ten, ngaySinh, chucVu = null, soDienThoai, soNgayLam, soNgayDiTre, soGioTangCa;
        boolean gioiTinh;
        Nguoi y = null;
        ma = txtID.getText();
        ten = txtTen.getText();
        ngaySinh = txtNgaySinh.getText();
        soDienThoai = txtDienThoai.getText();
//        soNgayLam = Double.parseDouble(txtSoNgayLam.getText());
//        soNgayDiTre = Double.parseDouble(txtSoNgayDiTre.getText());
//        soGioTangCa = Double.parseDouble(txtSoGioTangCa.getText());
        soNgayLam = txtSoNgayLam.getText();
        soGioTangCa = txtSoGioTangCa.getText();
        soNgayDiTre = txtSoNgayDiTre.getText();

        gioiTinh = gioiTinhNam.isSelected(); //1)sai cho boolean

        int index = cbbChucVu.getSelectedIndex();
        if (index >= 0) {
            chucVu = cbbChucVu.getItemAt(index);
        }
        String chucVu1 = null;
        chucVu1 = chucVu.substring(0, 2);//2 ky tu 
        //ma.isEmpty() la nếu (mã rỗng)   và !ma.isEmpty() là nếu mã không rỗng
        if (!ma.isEmpty() && !ten.isEmpty() && !ngaySinh.isEmpty() && !chucVu.isEmpty() && !soDienThoai.isEmpty() && !soNgayLam.isEmpty() && !soNgayDiTre.isEmpty() && !soGioTangCa.isEmpty()) {
            double snl = Double.parseDouble(soNgayLam);
            double sgtc = Double.parseDouble(soGioTangCa);
            double sndt = Double.parseDouble(soNgayDiTre);
            if (ma.length() > 0 && ten.length() > 0 && ngaySinh.length() > 0 && soDienThoai.length() > 0
                    && soGioTangCa.length() > 0 && soNgayDiTre.length() > 0 && soNgayLam.length() > 0) {
                if (chucVu1.trim().equalsIgnoreCase("Th".trim())) {
                    y = new ThucTapSinh(ma, ten, ngaySinh, gioiTinh, chucVu, soDienThoai, snl, sndt, sgtc);
                } else if (chucVu1.trim().equalsIgnoreCase("Nh".trim())) {
                    y = new NhanVien(ma, ten, ngaySinh, gioiTinh, chucVu, soDienThoai, snl, sndt, sgtc);
                } else if (chucVu1.trim().equalsIgnoreCase("Ph".trim())) {
                    y = new PhoPhong(ma, ten, ngaySinh, gioiTinh, chucVu, soDienThoai, snl, sndt, sgtc);
                } else if (chucVu1.trim().equalsIgnoreCase("Tr".trim())) {
                    y = new TruongPhong(ma, ten, ngaySinh, gioiTinh, chucVu, soDienThoai, snl, sndt, sgtc);
                } else if (chucVu1.trim().equalsIgnoreCase("Gi".trim())) {
                    y = new GiamDoc(ma, ten, ngaySinh, gioiTinh, chucVu, soDienThoai, snl, sndt, sgtc);
                }
            }
            if (n == 0) {// lay thằng đầu tiên 
                a.add(y);
                n++;
            }
            for (int i = 0; i < a.size(); i++) { // check thằng đầu với thằng nhập vào  
                if (ma.trim().equalsIgnoreCase(a.get(i).getMa().trim())) {
                    if (n != 1) {
                        JOptionPane.showMessageDialog(rootPane, "Mã bị trùng ! vui lòng nhập lại");
                        break;
                    }
                } else {
                    dem++;
//                    System.out.println("dem : " + dem);
//                    System.out.println("a.size : " + a.size());
                    if (dem == a.size()) {
                        a.add(y);
                        break;
                    }
                }
            }
            n++;
//            a.add(y);
            showResult();
        } else if (ma.isEmpty()) {
//              JOptionPane.showMessageDialog(rootPane, "Mã không được để trống", "Thông báo", HEIGHT);
            JOptionPane.showMessageDialog(null, "Mã không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (ngaySinh.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ngày sinh không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (chucVu.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chức vụ không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (soDienThoai.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (soNgayLam.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Số ngày làm không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (soNgayDiTre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Số ngày đi trễ không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (soGioTangCa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Số giờ tăng ca không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Thông tin không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void btNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapLaiActionPerformed
        // TODO add your handling code here:
        //nhập lại
        txtDienThoai.setText("");
        txtSoGioTangCa.setText("");
        txtID.setText("");
        txtNgaySinh.setText("");
        txtSoNgayDiTre.setText("");
        txtSoNgayLam.setText("");
        txtTen.setText("");
        gioiTinhNam.setSelected(true);
        cbbChucVu.setSelectedIndex(0);
    }//GEN-LAST:event_btNhapLaiActionPerformed

    private void btDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocFileActionPerformed
        // TODO add your handling code here:
        //doc file
        JFileChooser fc = new JFileChooser("D://");
        fc.showOpenDialog(this);
        String tenFile = fc.getSelectedFile().getPath();
        x.docFile(tenFile);//tenfile
        a = x.getA();
        JOptionPane.showMessageDialog(rootPane, "Mở file thành công");
        showResult();
    }//GEN-LAST:event_btDocFileActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
//        while (model.getRowCount() > 0){
//            model.removeRow(0);
//        }
        int removeIndex = tableHienThi.getSelectedRow();//click len bang thi lay duoc chi so 
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một dòng rồi xóa !");
        } else {
            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa ? ");
            if (JOptionPane.YES_OPTION == choice) {
                a.remove(removeIndex);
            } else {

            }

        }

        showResult();
    }//GEN-LAST:event_btXoaActionPerformed
    int i = 0;
    private void btSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSapXepActionPerformed
        // TODO add your handling code here: 

        btTangDan.setVisible(true);
        btGiamDan.setVisible(true);
        btTheoTen.setVisible(true);
        btSoNgayLam.setVisible(true);
        btGioiTinhNam.setVisible(true);
        btChucVuCao.setVisible(true);
        btChucVuThap.setVisible(true);
        btGioiTInhNu.setVisible(true);
        i++;
//        System.out.println("i : " + i);
        if (i % 2 == 0) {
            btTangDan.setVisible(false);
            btGiamDan.setVisible(false);
            btTheoTen.setVisible(false);
            btSoNgayLam.setVisible(false);
            btGioiTinhNam.setVisible(false);
            btChucVuCao.setVisible(false);
            btGioiTInhNu.setVisible(false);
            btChucVuThap.setVisible(false);
        } else {
            btTangDan.setVisible(true);
            btGiamDan.setVisible(true);
            btTheoTen.setVisible(true);
            btSoNgayLam.setVisible(true);
            btGioiTinhNam.setVisible(true);
            btChucVuCao.setVisible(true);
        }
    }//GEN-LAST:event_btSapXepActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn làm mới danh sách ?");
        if (JOptionPane.YES_OPTION == choice) {
            for (int i = 0; i < a.size(); i++) {
                a.remove(a.get(i));
                i--;
            }

            for (int i = 0; i < b.size(); i++) {
                b.remove(b.get(i));
                i--;
            }
        } else {

        }
        showResult();
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void cbbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucVuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbbChucVuActionPerformed

    private void gioiTinhNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gioiTinhNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gioiTinhNuActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);//đóng


    }//GEN-LAST:event_btThoatActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        // TODO add your handling code here:
        //tim kiem 
        for (int i = 0; i < a.size(); i++) {
            b.add(a.get(i));
        }//them a vao b 
        for (int i = 0; i < a.size(); i++) {
            a.remove(a.get(i));
            i--;
        }//xoa all a

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i).getMa().trim().equalsIgnoreCase(tfTimKiem.getText().trim())) {
                a.add(b.get(i));//a.add
            }
        }
        showResult();
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void btLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("D://");
        fc.showSaveDialog(this);
        String tenFile = fc.getSelectedFile().getPath();
        x.ghiFile(tenFile);


    }//GEN-LAST:event_btLuuFileActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed
        // TODO add your handling code here:
        //JtextFile
        Nguoi y = a.get(0);
        Nguoi z = a.get(0);
        for (Nguoi x : a) {
            if (x.soNgayLam >= y.soNgayLam && x.soGioTangCa >= y.soGioTangCa && x.soNgayDiTre <= y.soNgayDiTre) {
                y = x;
            }

        }

        for (Nguoi x : a) {
            if (x.soNgayLam < z.soNgayLam) {
                z = x;
            }

        }
        this.jtThongBao.setText("Nguoi cham chi nhat cong ty la :\n " + y + "\n"
                + "Nguoi co kha nang bi duoi viec nhat cong ty la :\n " + z + "\n");


    }//GEN-LAST:event_btThongKeActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        jtThongBao.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btTangDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTangDanActionPerformed
        // TODO add your handling code here:
//        x.sapXepTheoLuongTangDan();
//        a = x.getA();
        Collections.sort(a, (a, b) -> (int) (a.getThanhTien() - b.getThanhTien()));//lambda
        showResult();//a->b  tăng
    }//GEN-LAST:event_btTangDanActionPerformed

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
        //tim kiem  


    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void btGiamDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGiamDanActionPerformed
        // TODO add your handling code here:
        Collections.sort(a, (a, b) -> (int) (b.getThanhTien() - a.getThanhTien()));//lambda
        showResult();//b-> a giảm

    }//GEN-LAST:event_btGiamDanActionPerformed

    private void btThemMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btThemMoiFocusLost

    }//GEN-LAST:event_btThemMoiFocusLost

    private void btTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTheoTenActionPerformed
        // TODO add your handling code here:
        Collections.sort(a, new Comparator<Nguoi>() {
            @Override
            public int compare(Nguoi o1, Nguoi o2) {
                return o2.getTen().compareTo(o1.getTen());
            }

        });

        showResult();
    }//GEN-LAST:event_btTheoTenActionPerformed

    private void txtSoNgayLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNgayLamActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtSoNgayLamActionPerformed

    private void txtSoNgayLamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoNgayLamFocusLost

    }//GEN-LAST:event_txtSoNgayLamFocusLost

    private void btChucVuCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChucVuCaoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < b.size(); i++) {
            b.remove(b.get(i));
            i--;
        }
        for (int i = 0; i < a.size(); i++) {
            b.add(a.get(i));
        }
        for (int i = 0; i < a.size(); i++) {
            a.remove(a.get(i));
            i--;
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof GiamDoc) {

                a.add(b.get(i));
            }
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof TruongPhong) {
                a.add(b.get(i));
            }
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof PhoPhong) {
                a.add(b.get(i));
            }
        }
        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof NhanVien) {
                a.add(b.get(i));
            }
        }
        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof ThucTapSinh) {
                a.add(b.get(i));
            }
        }

        showResult();//b-> a giảm
    }//GEN-LAST:event_btChucVuCaoActionPerformed

    private void btGioiTinhNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGioiTinhNamActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < b.size(); i++) {
            b.remove(b.get(i));
            i--;
        }
        for (int i = 0; i < a.size(); i++) {
            b.add(a.get(i));
        }
        for (int i = 0; i < a.size(); i++) {
            a.remove(a.get(i));
            i--;
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i).isGioiTinh() == true) {

                a.add(b.get(i));
            }
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i).isGioiTinh() == false) {
                a.add(b.get(i));
            }
        }

        showResult();//b-> a giảm
    }//GEN-LAST:event_btGioiTinhNamActionPerformed

    private void btSoNgayLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSoNgayLamActionPerformed
        // TODO add your handling code here:
        Collections.sort(a, (a, b) -> (int) (b.getSoNgayLam() - a.getSoNgayLam()));//lambda
        showResult();//b-> a giảm
    }//GEN-LAST:event_btSoNgayLamActionPerformed

    private void btThoiViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoiViecActionPerformed
        // TODO add your handling code here:
        int removeIndex = tableHienThi.getSelectedRow();//click len bang thi lay duoc chi so 
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một nguời!");
        } else {
            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn loại bỏ nhân viên này ? ");
            if (JOptionPane.YES_OPTION == choice) {
                a.remove(removeIndex);
            } else {

            }

        }

        showResult();
    }//GEN-LAST:event_btThoiViecActionPerformed

    private void btGioiTInhNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGioiTInhNuActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < b.size(); i++) {
            b.remove(b.get(i));
            i--;
        }
        for (int i = 0; i < a.size(); i++) {
            b.add(a.get(i));
        }
        for (int i = 0; i < a.size(); i++) {
            a.remove(a.get(i));
            i--;
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i).isGioiTinh() == false) {

                a.add(b.get(i));
            }
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i).isGioiTinh() == true) {
                a.add(b.get(i));
            }
        }

        showResult();//b-> a giảm
    }//GEN-LAST:event_btGioiTInhNuActionPerformed

    private void btChucVuThapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChucVuThapActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < b.size(); i++) {
            b.remove(b.get(i));
            i--;
        }
        for (int i = 0; i < a.size(); i++) {
            b.add(a.get(i));
        }
        for (int i = 0; i < a.size(); i++) {
            a.remove(a.get(i));
            i--;
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof ThucTapSinh) {
                a.add(b.get(i));
            }
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof NhanVien) {
                a.add(b.get(i));
            }
        }
        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof PhoPhong) {
                a.add(b.get(i));
            }
        }
        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof TruongPhong) {
                a.add(b.get(i));
            }
        }

        for (int i = 0; i < b.size(); i++) {
            if (b.get(i) instanceof GiamDoc) {
                a.add(b.get(i));
            }
        }
        showResult();//b-> a giảm
    }//GEN-LAST:event_btChucVuThapActionPerformed

    public void showResult() {//lay du lieu ( tra về dữ liệu ) // in ra du lieu tren bang
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (Nguoi y : a) {
            model.addRow(new Object[]{
                y.getMa(), y.getTen(), y.getNgaySinh(), (y.isGioiTinh() ? "Nam" : "Nu"), y.getSoDienThoai(), y.getChucVu(), y.getSoNgayLam(),
                y.getSoNgayDiTre(), y.getSoGioTangCa(), y.phuCap(), y.getThanhTien()
            });
        }
    }

//    public void showResult1() {//lay du lieu ( tra về dữ liệu ) 
//        Nguoi y = a.get(a.size() - 1);//xet mang 
//        model.addRow(new Object[]{//không giới hạn sl phần từ của mảng 
//            y.getMa(), y.getTen(), y.getNgaySinh(), (y.isGioiTinh() ? "Nam" : "Nu"), y.getSoDienThoai(), y.getChucVu(), y.getSoNgayLam(),
//             y.getSoNgayDiTre(), y.getSoGioTangCa(), y.phuCap(), y.getThanhTien()
//        });
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Nhan_Vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Nhan_Vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Nhan_Vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Nhan_Vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quan_Ly_Nhan_Vien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChucVuCao;
    private javax.swing.JButton btChucVuThap;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDocFile;
    private javax.swing.JButton btGiamDan;
    private javax.swing.JButton btGioiTInhNu;
    private javax.swing.JButton btGioiTinhNam;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btLuuFile;
    private javax.swing.JButton btNhapLai;
    private javax.swing.JButton btSapXep;
    private javax.swing.JButton btSoNgayLam;
    private javax.swing.JButton btTangDan;
    private javax.swing.JButton btThemMoi;
    private javax.swing.JButton btTheoTen;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btThoiViec;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JRadioButton gioiTinhNam;
    private javax.swing.JRadioButton gioiTinhNu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtThongBao;
    private javax.swing.JTable tableHienThi;
    private javax.swing.JTextField tfTimKiem;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoGioTangCa;
    private javax.swing.JTextField txtSoNgayDiTre;
    private javax.swing.JTextField txtSoNgayLam;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
